using CustomerRelationshipManagement.Samples;
using Xunit;

namespace CustomerRelationshipManagement.EntityFrameworkCore.Applications;

[Collection(CustomerRelationshipManagementTestConsts.CollectionDefinitionName)]
public class EfCoreSampleAppServiceTests : SampleAppServiceTests<CustomerRelationshipManagementEntityFrameworkCoreTestModule>
{

}
