using CustomerRelationshipManagement.EntityFrameworkCore;
using Xunit;

namespace CustomerRelationshipManagement.EntityFrameworkCore;

public class CustomerRelationshipManagementEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<CustomerRelationshipManagementEntityFrameworkCoreFixture>
{

}
