using Volo.Abp;

namespace CustomerRelationshipManagement.EntityFrameworkCore;

public abstract class CustomerRelationshipManagementEntityFrameworkCoreTestBase : CustomerRelationshipManagementTestBase<CustomerRelationshipManagementEntityFrameworkCoreTestModule>
{

}
