using Xunit;

namespace CustomerRelationshipManagement.EntityFrameworkCore;

[CollectionDefinition(CustomerRelationshipManagementTestConsts.CollectionDefinitionName)]
public class CustomerRelationshipManagementEntityFrameworkCoreCollection : ICollectionFixture<CustomerRelationshipManagementEntityFrameworkCoreFixture>
{

}
