using CustomerRelationshipManagement.Samples;
using Xunit;

namespace CustomerRelationshipManagement.EntityFrameworkCore.Domains;

[Collection(CustomerRelationshipManagementTestConsts.CollectionDefinitionName)]
public class EfCoreSampleDomainTests : SampleDomainTests<CustomerRelationshipManagementEntityFrameworkCoreTestModule>
{

}
